# Generated by Django 4.0.4 on 2022-04-26 19:06

from django.db import migrations, models
import news_website_project.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[news_website_project.accounts.validators.MinDateValidator, news_website_project.accounts.validators.MaxDateValidator]),
        ),
    ]
