# Generated by Django 4.0.4 on 2022-04-26 19:09

import django.core.validators
from django.db import migrations, models
import news_website_project.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_newsuser_is_active_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), news_website_project.accounts.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), news_website_project.accounts.validators.validate_only_letters]),
        ),
    ]
