# Generated by Django 4.0.4 on 2022-04-26 19:15

import datetime
from django.db import migrations, models
import news_website_project.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_date_of_birth_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[news_website_project.accounts.validators.MinDateValidator(datetime.date(1920, 1, 1))]),
        ),
    ]
